version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jre

    steps:
      - checkout  # Récupère le code source depuis le référentiel Git
      - run:
          name: Build and Test
          command: ./gradlew build  # Remplacez cette commande par celle nécessaire pour construire votre projet

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
